### ISSUE TITLE
How to use it with UI Router and also with Lazy Loading ?

### ISSUE THREAD

**Issue by LokeshBoran** [tnicola/ngx-joyride#10]
How to use it with UI Router and also with Lazy Loading ?

**Comment by tnicola** [comment]
Hi @LokeshBoran,
I don't have a solution for ui-router or a generic Router. The only thing you can do now (even if you're not using it and it's not nice for you) is to add `@angular/router` to your dependencies. Then, for lazy loaded modules, you should import the JoyrideModule in your AppModule using `JoyrideModule.forRoot()`. In your lazy loaded feature modules import `JoyrideModule.forChild()`.

**Comment by LokeshBoran** [comment]
Ok, So @tnicola when it will support angular 6? Right now it is not supporting angular 6, right?

**Comment by tnicola** [comment]
Yes, you're right, officially Angular 6 is not supported but it will be soon. In the meanwhile it should be there a workaround here: https://github.com/tnicola/ngx-joyride/issues/8 (I've not tested it yet).

**Comment by AlanNgHub** [comment]
Hi somehow is issue happen intermittently for different page routing 
core.js:1598 ERROR TypeError: Cannot read property 'targetViewContainer' of undefined
Something it works but sometimes hits this error.Thanks

**Comment by tnicola** [comment]
@AlanNgHub Which version of the library are you using?How many steps do you use in total?How many steps per page?Are there some corner cases in which this issue always happen?
The more details you can give to me, the more I can help you!

**Comment by AlanNgHub** [comment]
My gut feeling is that the screen not loaded yet and the framework try to select it? Do you think so?
Thanks a lot :)

**Comment by tnicola** [comment]
Hi @AlanNgHub , sorry for the late reply. Yes, that could be an option!Is your fourthStep always visible?Does it have some condition in which is not visible at all? Try the directive on another simple component in the same page. 

I'm  trying to find out what the problem could be and I will improve the error handling, logging something more helpful in the future. In the meanwhile, are you able to reproduce the error in a small repo/stackblitz? That would be great to understand the issue!

**Comment by lenichols** [comment]
I'm having the same thing targetViewContainer is the error i get when i use JoyrideModule.forChild(), same thing for JoyrideModule.forRoot() in using ui-router in a SPA. Any fixes for this yet? I am simply trying to navigate to another page during the joyride.

**Comment by tnicola** [comment]
Hi @lenichols ,

I have been struggling for a almost a month to find and solve this issue. Can you provide me more details, please?

- Which version of Angular are you using?
- Are you using ui-router ([https://github.com/ui-router/angular](https://github.com/ui-router/angular)) or the standard @angular/router?

If you can send a repo/stackblitz it would be great.

Thank you
