### ISSUE TITLE
At the time of production build its giving error

### ISSUE THREAD

**Issue by naveensain93** [tnicola/ngx-joyride#13]
When I am doing build for production server then its giving me a error i.e.
ERROR in ./node_modules/ngx-joyride/assets/images/close.svg
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
| <svg viewBox="0 0 25 25" height="25" width="25" xmlns="http://www.w3.org/2000/svg">
|     <line x1="1" y1="24"
|           x2="24" y2="1"
 @ ./node_modules/ngx-joyride/esm5/ngx-joyride.esm.js 1:17918-17955
 @ ./dist/server/main.bundle.js
 @ ./server.ts @tnicola @giorgiapitteri

**Comment by tnicola** [comment]
Hi @naveensain93,

How are you building?Do you use Webpack or Angular-CLI? Which versions? I see `./dist/server/main.bundle.js`, I suppose you're using Angular SSR (Universal), right?

**Comment by tnicola** [comment]
Issue fixed. The library is now compatible with Angular SSR. Check out the new 2.1.1 version.

**Comment by naveensain93** [comment]
Hi @tnicola ,
Thanks for looking this.
And thank you for resolving this issue. Now I will take update and if I face any issue again then I will let you know. :)

**Comment by tnicola** [comment]
Closing the issue!
