### ISSUE TITLE
Help Request: getting "Cannot read property 'startTour' of undefined"

### ISSUE THREAD

**Issue by sted6** [tnicola/ngx-joyride#142]
I apologize if this is the wrong place for this, but I couldn't find another way to reach out for assistance. It's not an issue with the package but instead just a lack in my knowledge of it that's the issue.

I imported the joyrideModule into my app.module:

`import { JoyrideModule } from 'ngx-joyride';`

`@NgModule({
  declarations: [
    AppComponent,
  ],
  imports: [
    JoyrideModule.forRoot(),
  ]`

(Maybe the issue is above. The app I am working on utilizes a root-routing module, where the browser module is imported...I just thought of this but does the JoyrideModule needs to be imported in the same module where the browser module is imported?)

Then inside the app.component.ts file:

`import { JoyrideService } from 'ngx-joyride';`

`ngOnInit() {
    setTimeout(this.startJoyride, 1000)
  }`

`startJoyride() {
    console.log('Joyride Started');
    this.joyrideService.startTour(
      {
        steps: ['dashboard@dashboard'],
        showPrevButton: false,
        stepDefaultPosition: 'top',
        themeColor: '#212f23'
      } 
    );
  }`

I'm seeing that console log ('Joyride Started'), and then the error. It seems the issue is with the way I'm importing the joyridemodule.

My first step is located in another component template called dashboard:

`<div joyrideStep="dashboard" 
         [title]="'Welcome to your Dashboard'"
         [text]="'This is where you can find all your widgets!'"
         class="desktop-dashboard">`

The dashboard module:

`import { JoyrideModule } from 'ngx-joyride';`

`@NgModule({
  imports: [ JoyrideModule.forChild() ]
`
I also tried removing forChild() to no avail.

Thank you so much for any help you can provide!

Again, I apologize if this is the wrong place to look for assistance.

**Comment by SharadaRamji** [comment]
Hi, @sted6 Please ensure that you have provided your JoyRideService in the construction of your component like constructor(public joyrideService: JoyrideService). The error is due to the fact that the joyrideService doesn't have any value

**Comment by sted6** [comment]
> Hi, @sted6 Please ensure that you have declared the JoyRideService in the constructor of your component like constructor(public joyrideService: JoyrideService). The error is due to the fact that the joyrideService doesn't have any value

Hey Sharada, thanks I did use dependency injection to define the service in the constuctor so that was not the issue.

That being said, the issue was with the way the routing was structured in the project. Closing now. Thanks!
