### ISSUE TITLE
TypeError: sink._addParentTeardownLogic is not a function

### ISSUE THREAD

**Issue by fanyak** [tnicola/ngx-joyride#17]
I get
TypeError: sink._addParentTeardownLogic is not a function
    at ReplaySubject.push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe (Observable.js:26)

when running ngx-joyride with:
rxjs -v 6.3.2

Could you help?

**Comment by tnicola** [comment]
Hi @fanyak ,
It seems a problem related to the latest version of rxjs. Have you recently upgraded your angular version to 6 with `ng update`? There's an issue opened in rxjs: https://github.com/ReactiveX/rxjs/issues/4070, it seems an hot topic in these days. Maybe someone has found a solution: https://github.com/ReactiveX/rxjs/issues/4070#issuecomment-419041214. Anyway, I'll check the library to be completely sure.
