### ISSUE TITLE
Background flickering between steps.

### ISSUE THREAD

**Issue by desiv** [tnicola/ngx-joyride#18]
Would it be possible to fix the flickering when the steps are switching?

**Comment by tnicola** [comment]
Hi @desiv ,
Yes it's possible. I already have a solution in my mind for that. I'll try to fix it in the next days. 
Thanks!

**Comment by tnicola** [comment]
The flickering issue should have been resolved in v 2.2.0. Let me know if you still have these issues after upgrading the library.
