### ISSUE TITLE
Can't find step in Modal

### ISSUE THREAD

**Issue by sted6** [tnicola/ngx-joyride#187]
**Describe the bug**
The package can't find DOM elements located in a modal.

**To Reproduce**
1. Build a modal.
2. Create a function that opens the modal from another component.
3. Assign that function to a step's (next) event.
4. Make the next step an element inside the modal.
5. Set a waitingTime to allow plenty of time for the modal to open if you want to see that that isn't the problem.

**Expected behavior**
The step to be found in the DOM.

**Details (please complete the following information):**
 Chrome Version 83.0.4103.97 (Official Build) (64-bit)
We have many dependencies...I don't think any of them are at all related to this issue though.

**Additional context**
After enabling logs the problem is obviously that it just can't access the modal elements for some reason. Even after after clicking prev on the next step, to go back to the modal step, when the modal has clearly finished loading on the page, and the element still can't be found in the dom. The step target elements are not hidden behind any directive statements.

**Comment by sted6** [comment]
This was just me being stupid. Not an issue.

**Comment by Saqib92** [comment]
Can you write down the steps you used to open modal? or it will automatically open modal to show tour step? I am using bootstrap 3.
