### ISSUE TITLE
Angular 10 ModuleWithProviders<T> is Required

### ISSUE THREAD

**Issue by unboxedsolutions** [tnicola/ngx-joyride#195]
**Angular 10 ModuleWithProviders Compatibility**
In Angular 10, ModuleWithProviders must be ModuleWithProviders<T>

**To Reproduce**
1. Create an Angular 10 project
2. Install ngx-joyride
3. Run ng build

**Additional context**
Just noticed that the joyride.module.d.ts uses

`export declare const routerModuleForChild: ModuleWithProviders;`

instead of

`export declare const routerModuleForChild: ModuleWithProviders<any>;`

If there is an easy way to fix this on my end or it's just pilot error, I'd appreciate the guidance. Thanks!

**Comment by vikaspotluri123** [comment]
@tnicola I think this can be closed now. Thank you @tnicola, @lehoffma, and @alexsukhodolsky for updating the compatibility of this lib 🎉

**Comment by tnicola** [comment]
Thanks @vikaspotluri123 . @unboxedsolutions I'm going to close this, please let me know if you still see this error.

**Comment by tiagomartins91** [comment]
Thanks :)
