### ISSUE TITLE
Error after update to version 2.2.0

### ISSUE THREAD

**Issue by fernandosimoes** [tnicola/ngx-joyride#20]
Hey man, how are you, i hope that will be everything all right =)

Man, after update the component to the new version i started to receive some errors in my "console.log" and by conseguence, my system broken.

I wiil attach one image of my console to be more clear what is the error. I'm receiving this error 164 times in console.

could you help me with this error?

I found one possible solution in the google, that is change in some places of my code, to be more exactly where i'm using: 

providers: [{provide: ......, useClass: .....}]  to providers: [{provide: ......, useValue: .....}], this change had a great impact on my system, then again, could you help me =/?

Angular Version: 5

![image](https://user-images.githubusercontent.com/3368885/46497093-fd903e00-c7ef-11e8-8050-3e74e391c30d.png)

**Comment by Boggimedes** [comment]
I believe I'm getting the same failure.  I get the same (not a constructor) error in my console log, however this is only when I build for production.  If I build for dev everything works fine, no warnings or errors.  If I build for production I get these warnings:

WARNING in ./src/app/app.module.ngfactory.js 159:7340-7346
"export 'ɵa' (imported as 'i57') was not found in 'ngx-joyride'

WARNING in ./src/app/app.module.ngfactory.js 159:7332-7338
"export 'ɵa' (imported as 'i57') was not found in 'ngx-joyride'

WARNING in ./src/app/organization/companies/companies.component.ngfactory.js 81:159-164
"export 'ɵa' (imported as 'i6') was not found in 'ngx-joyride'

WARNING in ./src/app/_components/modal/donation/donation.component.ngfactory.js 159:345-350
"export 'ɵa' (imported as 'i9') was not found in 'ngx-joyride'

WARNING in ./src/app/_components/modal/donation/donation.component.ngfactory.js 340:1274-1279
"export 'ɵa' (imported as 'i9') was not found in 'ngx-joyride'

WARNING in ./src/app/_components/modal/donation/donation.component.ngfactory.js 528:1315-1320
"export 'ɵa' (imported as 'i9') was not found in 'ngx-joyride'

(etc)


Then in the console. I get "n is not a constructor"

**Comment by tnicola** [comment]
Hi guys, 
Sorry for the delay, I'm having a look. I'll let you know soon!

**Comment by tnicola** [comment]
@fernandosimoes and @Boggimedes , 
there was an error in the barrel file. I forgot to export a service, sorry about that. I fixed it and published a new version: 2.2.1.

**Comment by fernandosimoes** [comment]
Thank you man 😁

**Comment by Ciprian95** [comment]
Thanks man 👍
