### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by skobak** [tnicola/ngx-joyride#208]
**Describe the bug**
When I run 
```ng build --prod```
 I got the following error:

```
ERROR in ./node_modules/ngx-joyride/fesm5/ngx-joyride.js
Module build failed (from ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js):
TypeError: Cannot read property 'kind' of undefined
```

**Expected behavior**
Should build the bundle

**Details (please complete the following information):**
  "@angular/core": "^7.2.10",
 "ngx-joyride": "^2.3.1",
  "typescript": "3.2.4",

What could be the cause of the problem?

Best, Alex

**Comment by carrie-xin** [comment]
I have the same problem, but `ng build` works fine, Does anyone know the reason

**Comment by carrie-xin** [comment]
I've solved this problem in my project according to [this issue](https://github.com/ckeditor/ckeditor4-angular/issues/78).
It's seems like the problem of angular devkit version. In my project , i  installed latest devkit packages, then ` ng build --prod` worked
```
npm i @angular-devkit/build-optimizer@latest --save-dev
```

package.json：
```
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.13.8",
    "@angular-devkit/build-optimizer": "^0.1000.5",
    "@angular/cli": "~7.3.8",
    "@angular/compiler-cli": "~7.2.12",
    "@angular/language-service": "~7.2.12",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~3.2.4"
     ...
  }
```

**Comment by skobak** [comment]
thanks @carrie-xin , your solution works!

**Comment by ymongo** [comment]
thank you, solved as well!

**Comment by tnachy** [comment]
> I've solved this problem in my project according to [this issue](https://github.com/ckeditor/ckeditor4-angular/issues/78).
> It's seems like the problem of angular devkit version. In my project , i installed latest devkit packages, then ` ng build --prod` worked
> 
> ```
> npm i @angular-devkit/build-optimizer@latest --save-dev
> ```
> 
> package.json：
> 
> ```
>   "devDependencies": {
>     "@angular-devkit/build-angular": "^0.13.8",
>     "@angular-devkit/build-optimizer": "^0.1000.5",
>     "@angular/cli": "~7.3.8",
>     "@angular/compiler-cli": "~7.2.12",
>     "@angular/language-service": "~7.2.12",
>     "ts-node": "~7.0.0",
>     "tslint": "~5.11.0",
>     "typescript": "~3.2.4"
>      ...
>   }
> ```

Hi, I tried this solution but it does not work for me, I am using angular 8 and my typescript version  is  3.5.3
