### ISSUE TITLE
Steps cannot find route in angular

### ISSUE THREAD

**Issue by macangular** [tnicola/ngx-joyride#21]
I'm trying to route the steps through multiple components in angular 6 that has multiple routers but when I'm trying to route to it i keep getting this error no matter what i do.

ERROR TypeError: Cannot read property 'targetViewContainer' of undefined

Joyride cant find where the next step is because its under the same route tag but different component

**Comment by macangular** [comment]
I figured out the problem you need to put JoyrideModule.forChild() in every module

**Comment by tnicola** [comment]
Good you've found the problem!I'll try to return better errors.
