### ISSUE TITLE
Will ngx-joyride work with Angular 7?

### ISSUE THREAD

**Issue by khailuvsmilktea** [tnicola/ngx-joyride#23]
If not, any other product tour library you'd recommend? (for Angular 7)

**Comment by tnicola** [comment]
Hi @khailuvsmilktea ,

There are no breaking changes in Angular 7 related to ngx-joyride implementation, so it should work fine. If you encounter any problem, please let me know and I'll update the library. 
Thanks

**Comment by khailuvsmilktea** [comment]
Thanks!
