### ISSUE TITLE
Anchorless Step - How to create?

### ISSUE THREAD

**Issue by lenichols** [tnicola/ngx-joyride#26]
How do i set a step to be anchorless... i do not want it to be associated with any element on the page, i simply want to center it on the page and have it pop up. I saw this in the demo but no details on how to make this happen.

My Steps look like this: **steps: ['stepOne', 'stepTwo']**

**Comment by tnicola** [comment]
I hope to improve the overall documentation for the library. You can create an anchorless step just using the attribute `stepPosition="center"`. 

e.g.:
```
<joyrideStep joyrideStep="myCentralStep" stepPosition="center"></joyrideStep>
```
Try it out and let me know.

**Comment by lenichols** [comment]
Awweeeeeee! i know it was something simple :+1:

**Comment by lenichols** [comment]
Do i add it to a step? steps: ['center', 'stepOne', 'stepTwo'] ?

**Comment by tnicola** [comment]
Yes, sorry, you should add it to the steps array.

**Comment by shastaxc** [comment]
Attempting to use this method gives me the following error
![image](https://user-images.githubusercontent.com/7599524/58129779-8e355600-7be8-11e9-8630-a8f1c77bb376.png)
