### ISSUE TITLE
Steps depending on css animation

### ISSUE THREAD

**Issue by mbondoso** [tnicola/ngx-joyride#27]
Hi all,

I have a step that depends on the end of a css animation to be correctly positioned. 

Is there a way that I can navigate to the next step programmaticaly (ex: using the StepService) but that does not mess up with the rest of the flow?

I used this:
`this.joyrideStepService.next();
this.joyrideStepService.prev();`

but afterwards the flow was messed up with 2 popovers.

**Comment by tnicola** [comment]
Hi,

What I can suggest to you is using the `next` `@Output` event of the joyride directive. You can use a `setTimeout` to wait for the animation is finished. 

Lets suppose you have two steps "joy1" and "joy2" and the step "joy2" has an animation which requires 200ms to position the step correctly. You can use the "joy1" next event to do something (waiting in your case) before the "joy2" is rendered.

```
@Component({
  selector: 'app-component',
  template: `<div joyrideStep="joy1" title="title" (next)="onNext()">Hello!</div>
             <div joyrideStep="joy2" title="title2">My animated div</div>`
})
export class AppComponent {
  constructor(private readonly joyrideService: JoyrideService) { }

  onClick() {
    this.joyrideService.startTour(
      { steps: ['joy1', 'joy2']} // Your steps order
    );
  }

  onNext(){
    setTimeout(() => {
       // waiting...
    }, 200 );
  }
}
```

**Comment by mbondoso** [comment]
Hi,
I have tried that as my first aproach but it does not work, because execution is not blocked by the set timeout. When the setTimeout function occurs, the joy2 is already selected in the previous position in the dom.

**Comment by mbondoso** [comment]
@tnicola I have tried a different approach. I'll probably go with 2 separate tours and the second only starts after the timeout from the Done event of the Output.
