### ISSUE TITLE
How to assign a function to the "DONE" button?

### ISSUE THREAD

**Issue by lenichols** [tnicola/ngx-joyride#28]
I want the 'x' close button to behave differently than the 'done' button. Is there a way to assign a function to the done button without having to modify the package itself?

**Comment by tnicola** [comment]
Hi,

On the last step you can listen for the (done) @Output of the Joyride Directive and do whatever you like. 

```
@Component({
  selector: 'app-component',
  template: `<div joyrideStep="lastStep" title="title2" (done)="onDone()">Hello!</div>`
})
export class AppComponent {
  constructor() { }
  onDone() {
    // Do something
  }
}
```

After that the tour will be closed anyway.

**Comment by lenichols** [comment]
@tnicola when you click on "X" it dispatches an event call to done()...so does the "Done" button at the last step. How can i assign a different function to "X"?

**Comment by tnicola** [comment]
Hi @lenichols ,

For now there's no possibility to change the "X" behaviour but I can add the possibility to pass a callback function option. Can you give me an example of a function/action you'd like to perform? Just to think the better approach to implement this feature.

Anyway, another choice you can take right now is [Subscribing to startTour complete](https://github.com/tnicola/ngx-joyride#listen-for-events).
