### ISSUE TITLE
tour guide not showing

### ISSUE THREAD

**Issue by ajai06** [tnicola/ngx-joyride#306]
hi, I am trying to integrate ui tour guide in chrome-tabs. for that, I tried with 'ngx-joyride' which required an attribute name called "joyrideStep = 'name'".so while initing chrome tabs for all the chrome elements I manually append an attribute element.setAttributeNS(null,"joyrideStep", tab_id) . while consoling chrome elements, attribute value updated but tour guide not showing in any of the chrome tabs. i need to know this issue happening bcoz of ngx-joyride or chrome tabs. if anyone knows pls help me

```let all_left_panel_tabs = document.querySelectorAll(".left-panel-tab .chrome-tab");
all_left_panel_tabs.forEach((element) => {

        let tab_id = element.getAttribute('data-tab-id');
        element.setAttributeNS(null,"joyrideStep", tab_id);
        console.log(element);
})
this.joyrideService.startTour(
        { steps: ['backup','bookmarks','rvclean','workspace','settings','comments',],
          showCounter: true,
          themeColor: '#5a5e60'

        } // Your steps order
    )
"@angular/cli": "^6.2.9"
"chrome-tabs": "^5.4.0"
"ngx-joyride": "^2.3.1",
thanks !.

**Comment by tnicola** [comment]
Dear @ajai06 , is it your application written in Angular?Are you calling the startTour from a Service or a Component?

**Comment by ajai06** [comment]
Yes in angular  & from component

**Comment by tnicola** [comment]
Do you have any error log?
Is the component which is launching the tour in the same tab of all the other elements?
Are you trying to build a tour in which the steps are in different tabs?If this is the case, I don't see how Angular could communicate across tabs.

**Comment by ajai06** [comment]
all the elements from the same component only

**Comment by tnicola** [comment]
I've tried different solutions, triggering a change detection or running the code in Angular zone with NgZone but in the end none works. It seems it's not possible to attach a Directive to a Component at runtime. You cannot simply add an attribute dynamically to make it working, the attribute should be defined statically, ahead of time. It seems the Angular team is working on it: 

https://github.com/angular/angular/issues/6970 
https://github.com/angular/angular/issues/8785

Feel free to reach out if you find a solution to this

**Comment by ajai06** [comment]
sure, thank you.
