### ISSUE TITLE
[Feature Request] force close programmatically

### ISSUE THREAD

**Issue by JohnKimDev** [tnicola/ngx-joyride#37]
It would be nice to have a "stopTour" function. I have this use case that the application can be auto logged out due to an inactive timeout. And the auto logout can happen while the joyride overlay is on.  And when this happened, the joyride layout display is on stuck on the incorrect page.

**Comment by tnicola** [comment]
Hi @JohnKimDev ,
Thanks for the suggestion, this is a nice one!I'm going to work on this soon and I'll let you know once ready.

Nicola

**Comment by tnicola** [comment]
Check out the new version (2.2.6), the `stopTour` should be in place: https://github.com/tnicola/ngx-joyride#close-programmatically-the-tour

**Comment by JohnKimDev** [comment]
Thank you for implementing the feature!

**Comment by lenichols** [comment]
@tnicola thank you for adding this helpful close feature...

**Comment by himanshu-supplycopia** [comment]
> Thank you for implementing the feature!



> Check out the new version (2.2.6), the `stopTour` should be in place: https://github.com/tnicola/ngx-joyride#close-programmatically-the-tour

Hey @tnicola  thanks for making this guided tour it really helps me a lot but I have one issue if guided tour popup remains open and after session timeout joyride layout displays is on....i tried to call this "this.joyrideService.closeTour()" inside constructor to solve this issue but still joyride layout displays on after session timeout.....please tell me if I am doing something wrong ?

Any help would be appreciated on this.

**Comment by himanshu-supplycopia** [comment]
Hey @tnicola  thanks for making this guided tour it really helps me a lot but I have one issue if guided tour popup remains open and after session timeout joyride layout displays is on....i tried to call this "this.joyrideService.closeTour()" inside constructor to solve this issue but still joyride layout displays on after session timeout.....please tell me if I am doing something wrong ?

Any help would be appreciated on this.

**Comment by Himanshu-Niigaam** [comment]
Hey @tnicola thanks for making this guided tour it really helps me a lot but I have one issue if guided tour popup remains open and after session timeout joyride layout displays is on....i tried to call this "this.joyrideService.closeTour()" inside constructor to solve this issue but still joyride layout displays on after session timeout.....please tell me if I am doing something wrong ?

Any help would be appreciated on this.
