### ISSUE TITLE
[Feature Request] add optional wait between going to route and showing tour step

### ISSUE THREAD

**Issue by ArnoMyOnlinePresence** [tnicola/ngx-joyride#42]
Is it possible to add an optional time to wait before showing a step after going to the route defined in the step? For example in our app if you keep going to the next step it works perfectly as i build it so all the data is loaded for each page by the time the tour gets to it. But if you go back in the tour it needs to re-get some of the data in certain points and this causes the tour window to not be at the correct place as the place it needs to be does not yet exist

**Comment by tnicola** [comment]
Hi @ArnoMyOnlinePresence ,

Yes, it's possible, I will add this option, thanks.

**Comment by tnicola** [comment]
I've added `waitingTime` option in v2.2.9. For each step, it waits waitingTime milliseconds after going to the route before looking for the step. In the future I will add a timeout for searching automatically for steps without having to wait for each one of them.
