### ISSUE TITLE
Bug: Flash-Effect between Steps because of Backdrop.

### ISSUE THREAD

**Issue by Domvel** [tnicola/ngx-joyride#43]
**Describe the bug**
The screen is flashing between steps. Because there is a gap between two steps. The backdrop is removed in a frame. 

**To Reproduce**
1. Go to the current [demo](https://tnicola.github.io/ngx-joyride/)
2. Start the tour.
3. Click the *next*
4. See the error. Flashing screen. 

**Expected behavior**
The screen should not flash. The backdrop should be enabled until it is disabled or the tour ends.

**Screenshots**
![ngx-joyride-flash-bug](https://user-images.githubusercontent.com/35452565/53961951-293e8980-40ea-11e9-98a2-446635a6f725.gif)

**Browser:** Chrome Version 72.0.3626.121 (Official Build) (64-bit)

**Comment by tnicola** [comment]
Hi @Domvel ,

Which version of the library are you using? (The current is 2.2.8) Since this is an old bug, it has already been solved in #18 (The demo is not updated to the latest version) . Could be a regression anyway. Let me know.

Thanks

**Comment by Domvel** [comment]
Ok, great news. I just tried the demo (see link above). I didn't used it in my project, yet. Maybe you should update the demo? 🙂

**Comment by Domvel** [comment]
Close because of #18 and the gif ![](https://github.com/tnicola/ngx-joyride/raw/master/docs/joyride-tour.gif) of more recent version. I'll try it out ...
