### ISSUE TITLE
How to target a sub component

### ISSUE THREAD

**Issue by ThomasSchoenbeck** [tnicola/ngx-joyride#44]
let's say i have a root component which has two other components implemented.

```html
<app-root>
  <first joyrideStep="1"></first>
  <second joyrideStep="2"></second>
</app-root>
```

now the second component is a bit complex, and i want to highlight stuff inside that component, too.

```html
<!-- second.component.html -->
<div>
  <h1 joyrideStep="2-1">headline</h1>
  <span joyrideStep="2-2">specific content</span>
</div>
```

How can i set this up, so i can browse through all 4 steps? What do i need to do when the sub component does not have it's own route, but is part of the current page the user is viewing?

```ts
startTour() {
  this.joyrideService.startTour( { steps: [ '1', '2', '2-1', '2-2' ] } )
}
```

**Comment by ThomasSchoenbeck** [comment]
don't wory. it works exactly like it should.

my template had an issue, and while i was testing it, the <second> component was not in the correct state.

**Comment by tnicola** [comment]
Hi @ThomasSchoenbeck , 
I'm happy it's working fine. Do not hesitate to ask again if something is not working correctly.
