### ISSUE TITLE
No component factory found for JoyrideStepComponent.

### ISSUE THREAD

**Issue by cetincakiroglu** [tnicola/ngx-joyride#448]
(Angular 6)

Cannot see Joyride steps even tough module imported as described in the docs.

app.module.ts

```
import {JoyrideModule} from "ngx-joyride";

@NgModule({
 imports:[JoyrideModule.forRoot()]
})
```

Something broken in ngx-joyride node_module.
As can be seen from the screenshot, the joyrideStepComponent is not working properly.

![B2Metric ML Studio — Firefox Developer Edition 04-Aug-21 1_25_48 PM](https://user-images.githubusercontent.com/69278826/128165977-b79c0ad9-6d05-4d05-8f96-90f4acd64ebc.png)

**Comment by nilanmeegoda99** [comment]
I also got the same issue

core.js:1673 ERROR Error: Error: No component factory found for JoyrideStepComponent. Did you add it to @NgModule.entryComponents?
    at ngx-joyride.js:1464
    at ZoneDelegate../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.js:3811)
    at ZoneDelegate../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:420)
    at Zone../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:188)
    at ./node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask (zone.js:496)
    at ZoneTask.invoke (zone.js:485)
    at timer (zone.js:2054)

**Comment by nilanmeegoda99** [comment]
I would like to recommend using Driver.js library for onboard tour rather than ngx-joyride for Angular 6. It has some compatibility issues

**Comment by pravinkumarputta** [comment]
I'm also facing the same issue.

@nilanmeegoda99 Your solution is good.
But I've used this plugin at so many places in my project. It will take so much time to replace.

Does anyone have the solution for making it work????

**Comment by francescotrincia** [comment]
Try to set 

entryComponents: [JoyrideStepComponent],

in your app.module.ts
It worked for me

**Comment by dhiegoatencio** [comment]
> Try to set
> 
> entryComponents: [JoyrideStepComponent],
> 
> in your app.module.ts It worked for me

worked for me, however I don't know when angular team will remove this entryComponents
