### ISSUE TITLE
IE11 - did someone get it to work?

### ISSUE THREAD

**Issue by ThomasSchoenbeck** [tnicola/ngx-joyride#46]
Hi there,

The tour i build into my app using this library is working in chrome as expected. My company still uses IE11 a lot, so we have to support this browser as well.

Strangely the tour is not working in IE11. There is no error message, everything seems fine. The function itself has a console.log, so i know it get's executed.

the tour just does not appear on screen.

**Comment by tnicola** [comment]
Hi @ThomasSchoenbeck ,

I was trying to maintain a cross-browsers compatibility but I just verify that is not working anymore on IE11. I'm having a look, sorry about that.

**Comment by fabio-cometti** [comment]
Same issue using Microsoft Edge and Firefox. No errors in console but the tour doesn't start.
In Edge console the message "ngx-joyride:::Initializing the steps array." is logged, In Firefox no.
No problems in Chrome.

**Comment by tnicola** [comment]
It should be fixed now. Check out the new version 2.2.9.

**Comment by fabio-cometti** [comment]
> 
> 
> It should be fixed now. Check out the new version 2.2.9.

In now Edge it works fine. In Firefox now ngx-joyride events are logged in console but still the tour doesn't start. No errors in console

**Comment by tnicola** [comment]
Hi @fabio-cometti, 

Which version of Firefox are you using?Since it was already working for me.

**Comment by fabio-cometti** [comment]
65.0.2 64 bit. I attach a screenshot of the console
![Capture](https://user-images.githubusercontent.com/48474953/54588022-113c0380-4a22-11e9-92d2-b866f6d513c3.PNG)

**Comment by tnicola** [comment]
That's weird!I'm using the same version and it works!Can you please share your dependency list? (also via mail if you prefer)

**Comment by fabio-cometti** [comment]
Sure! Here:

"dependencies": {
    "@angular/animations": "^6.0.3",
    "@angular/cdk": "^6.4.7",
    "@angular/common": "^6.0.3",
    "@angular/compiler": "^6.0.3",
    "@angular/core": "^6.0.3",
    "@angular/flex-layout": "^6.0.0-beta.18",
    "@angular/forms": "^6.0.3",
    "@angular/http": "^6.0.3",
    "@angular/material": "^6.4.7",
    "@angular/platform-browser": "^6.0.3",
    "@angular/platform-browser-dynamic": "^6.0.3",
    "@angular/router": "^6.0.3",
    "@aspnet/signalr": "^1.1.0",
    "@ngrx/core": "^1.2.0",
    "@ngrx/effects": "^6.1.0",
    "@ngrx/store": "^6.1.0",
    "@ngrx/store-devtools": "^6.1.0",
    "@swimlane/ngx-charts": "^9.0.0",
    "@types/highcharts": "^5.0.22",
    "@types/lodash": "^4.14.119",
    "angular-highcharts": "^6.2.6",
    "bootstrap": "^4.2.1",
    "core-js": "^2.5.4",
    "font-awesome": "^4.7.0",
    "hammerjs": "^2.0.8",
    "highcharts": "^6.2.0",
    "jwt-decode": "^2.2.0",
    "lodash": "^4.17.10",
    "ngx-auth": "^4.0.0",
    "ngx-joyride": "^2.2.9",
    "replace-in-file": "^3.4.3",
    "rxjs": "^6.0.0",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.6.6",
    "@angular/cli": "~6.0.7",
    "@angular/compiler-cli": "^6.0.3",
    "@angular/language-service": "^6.0.3",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.2.1",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~1.7.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.0",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.3.0",
    "ts-node": "~5.0.1",
    "tslint": "~5.9.1",
    "typescript": "~2.9.0",
    "webpack-bundle-analyzer": "^3.1.0"
  }

**Comment by ThomasSchoenbeck** [comment]
Thanks a lot @tnicola . It's working in IE11 now/again.

**Comment by tnicola** [comment]
@fabio-cometti I've tried with your dependencies and everything seems working fine in Firefox 65.0.2 64 bit. Can you please try this in your Firefox browser?Does it work?

https://stackblitz.com/edit/ngx-joyride-demo-1

**Comment by fabio-cometti** [comment]
Ok, I'have found the problem: I have a <mat-icon> with a (click) event that start the tour. In firefox seems that <mat-icon> doesn't fire the event, so I wrapped it in a button and now it works.
So in firefox was not a problem of ngx-joyride.

Thanks for your support

**Comment by tnicola** [comment]
Glad you've found the problem. :) Thanks
