### ISSUE TITLE
Buttons text

### ISSUE THREAD

**Issue by LautaroLorenz** [tnicola/ngx-joyride#48]
Create a more simple set buttons text u.u

**Comment by tnicola** [comment]
Hi @LautaroLorenz ,

Do you mean an option to set the buttons text instead of using the templates?

**Comment by LautaroLorenz** [comment]
exactly, I was thinking of something like:
```
this.joyrideService.startTour(
    { 
        steps: ['firstStep', 'secondStep'],
        prevText: 'my prev text'
    } 
);
```

**Comment by tnicola** [comment]
@LautaroLorenz your right, it would simplify a lot the usage. I will add this in the next weeks.

**Comment by anvial** [comment]
Hi, and when we see this commit in the release? Very usefull feature

**Comment by tnicola** [comment]
Done, here the documentation: https://github.com/tnicola/ngx-joyride#custom-buttons-texts
