### ISSUE TITLE
Issue with multi page routing 

### ISSUE THREAD

**Issue by ajaydjalexander** [tnicola/ngx-joyride#50]
having issue once tour is navigate to different route

Step not found in the DOM. Check if it's hidden by *ngIf directive. 
Can you help me out in this issue.

**Comment by tnicola** [comment]
@ajaydjalexander Sorry for the late reply, can you please try to enable the logs and post here what heppens?

```
this.joyrideService.startTour(
      { steps: ['joy1', 'joy2'], logsEnabled: true}
);
```

Thanks,
Nicola

**Comment by ajaydjalexander** [comment]
@tnicola Thanks for your reply
I forgot to include JoyrideModule.forChild() in my module file so that why it's not working. Once I included this in module file everything is working fine for me.

Thanks

**Comment by tnicola** [comment]
Ah!Perfect then, thanks! I leave this reference for anyone else that could face your problem navigating to other pages:
https://github.com/tnicola/ngx-joyride#get-multi-pages-navigation .
