### ISSUE TITLE
Ngx-translate/core issue

### ISSUE THREAD

**Issue by rtcimi** [tnicola/ngx-joyride#51]
Initial translations variables gets picked up by joyride steps... But when I switch language... translations inside steps don't get updated?

Any idea?

**Comment by tnicola** [comment]
Hi @rtcimi ,

Yes, it makes sense. Since the Joyride steps are added to an array statically at the beginning. I think that's  the reason why translations are not updated accordingly. One solution could be to add a `refresh` method to the `joyrideService` to update the steps. Could that make sense to you?

**Comment by rtcimi** [comment]
Hi,

It does make sense of cours... current work around that I do is to use timeout, boolean and *ngIf on objectst with joyridestep... but this is realy dirty solution...

**Comment by tnicola** [comment]
Yes, it's really bad indeed. Which version of the library are you using?I'm asking because I've already solved the sync translations problem for title and text in a previous version of the library.

**Comment by rtcimi** [comment]
"ngx-joyride": "^2.2.9"

**Comment by rtcimi** [comment]
But at the end... the biggest problem that I have and don't know how to solve it is that I can't manage to use it on svg path or markers of Leaflet maps for example... any idea how to achive this?

**Comment by tnicola** [comment]
Nope, have you tried to place the svg inside a `<div>` element? I will investigate about this.

**Comment by rtcimi** [comment]
Well I did not try that because it is allready in the div but way down to the dom tree which is managed by/trought map library ... I manage to append html tags required by joyridestep on to svg path after it is created, but step does not get picked up by the library.

**Comment by tnicola** [comment]
@rtcimi For solving this issue I need to reproduce the problem first. If you have time could you please provide a stackblitz with Angular + Leaflet? Otherwise I will do it but it will require a bit more time.

**Comment by rtcimi** [comment]
Sorry @tnicola, i've just realised that I was using joyrideModule.forRoot() instead joyrideModule.forChild() in my child routes... now translations after changing language also working inside joystep title and content... So, based on title you can close issue.

Regarding to leaflet DOM and joyrideStep issue here it is example on top of some other example: https://angular-ngx-leaflet-tests-yqkpzb.stackblitz.io (or editor mode ... https://stackblitz.com/edit/angular-ngx-leaflet-tests-yqkpzb)

Greetings,
And tnx for the awesome module!
