### ISSUE TITLE
Two JoyrideSteps with same name

### ISSUE THREAD

**Issue by pirasalbe** [tnicola/ngx-joyride#54]
**Describe the bug**
Hi, I have two joyride steps with same name but in different tours and in different pages.
The first one is 
```
irregolari: {
        title: 'Irregolari',
        text:
          'Puoi visualizzare le irregolari”'
      }
```

The other one is 
```
irregolari: {
        stepPosition: 'center',
        title: 'Fatture irregolari',
        text:
          'Permette di visualizzare le irregolari”'
      },
```

When I start the tour in which I set the stepPosition, than I change page and start the other tour it uses the stepPosition of the other step.

**To Reproduce**
1. Create a page with `<h1 joyrideStep="firstStep" stepPosition="center" title="Page Title" text="Main title!">Text</h1>`
2. Create another page with `<h1 joyrideStep="firstStep" title="Page Title" text="Main title!">Text2</h1>`
3. Start the tour in the first page
4. Start the tour in the second page

**Expected behavior**
It should use default position in my example.

**Details (please complete the following information):**
 - Browser Chrome 73.0.3683.103
 - List of the dependencies with their version:

- "@angular-devkit/schematics": "^0.0.52",
-     "@angular/animations": "^7.0.0",
-     "@angular/cdk": "^7.0.0",
-     "@angular/common": "^7.0.0",
-     "@angular/compiler": "^7.0.0",
-     "@angular/core": "^7.0.0",
-     "@angular/forms": "^7.0.0",
-     "@angular/http": "^7.0.0",
-     "@angular/material": "^7.0.0",
-     "@angular/material-moment-adapter": "^7.0.0",
-     "@angular/platform-browser": "^7.0.0",
-     "@angular/platform-browser-dynamic": "^7.0.0",
-     "@angular/platform-server": "^7.0.0",
-     "@angular/router": "^7.0.0",
-     "ngx-joyride": "^2.2.9",

**Comment by tnicola** [comment]
Hi @pirasalbe,

I'm sorry for the late reply. Yes, it is true, despite the different tour, if you have two steps with the same name in a document, the tour will take only one, overriding the other. The thing I can't explain is how it's using the correct title and wrong step position, I expected both the title and the position to be wrong.

**Comment by pirasalbe** [comment]
I've changed the step name to avoid this bug, anyway I just checked and you are right, it uses also the wrong text and title.

**Comment by tnicola** [comment]
Ok, thanks for the update. The fact is that the step name should be unique across the entire DOM, at least until the library won't be aware of the presence of multiple tours. I would close this for now unless you are forced to have two steps with the same name.

**Comment by pirasalbe** [comment]
I'll use different names, that's fine.
Is it possibile that sometimes the title properties of a joyride step is also used as tooltip?

**Comment by absardev** [comment]
Hi @tnicola

**Comment by absardev** [comment]
Hi @tnicola  
I have implemented site tour by using joyrideSteps.it is working fine for only single page whenever routes changed it will close the tour. I tried multiple approaches like,

- when ever route changed and new component loaded I try to reinitialize the tour but it is not working and other similar approach like that but all are not working.
`this.joyrideService.startTour({
      steps: ['secondStep', 'thirdStep','fourStep@manage-assets','fiveStep@manage-assets','six@manage-assets'],
    }) .subscribe(
      (step) => {
        console.log(step);
        // this.currStep = step.name;
      },
      (error) => {
        console.log('tour error',error);
      },
      () => {
        console.log("tour finish!");
      }`
      when I reinitialized this in other component it will only run  this part console.log("tour finish!"); 
      please help me on this.
