### ISSUE TITLE
Instruction to get a central tour without attaching to a element

### ISSUE THREAD

**Issue by artoodeeto** [tnicola/ngx-joyride#55]
Hello, Sorry but where is the instruction to have a central tour without attaching on any element / target just like the third part on the demo? Also the instruction is miss leading about its being required but on central step it doesnt. Thank you.

**Comment by artoodeeto** [comment]
I also want to add. Is there a way to hide or remove the close button? Can we add this as an option if ever?

**Comment by tnicola** [comment]
Hi @artoodeeto ,
To add a central step you can do like this:
```
 <joyrideStep joyrideStep="centralStep" stepPosition="center"></joyrideStep>
```

**Comment by tnicola** [comment]
There's no way to hide the hide the close button. I will add an option to do so. In the meanwhile you can hide it via CSS:
```
img.joyride-step__close {
    display: none;
}
```

**Comment by artoodeeto** [comment]
@tnicola thank you for your response. I was already done with my task and did the same thing. thank you.
