### ISSUE TITLE
Getting error when importing JoyrideModule in lazy loaded module

### ISSUE THREAD

**Issue by SS2095** [tnicola/ngx-joyride#6]
I added Joyridemodule to a shared module that i imported into my lazy loaded modules.Getting the following error
Uncaught (in promise): Error: RouterModule.forRoot() called twice. Lazy loaded modules should use RouterModule.forChild() instead.
Error: RouterModule.forRoot() called twice. Lazy loaded modules should use RouterModule.forChild() instead.

If I only import it into the app module, I get this error
Cannot read property 'targetViewContainer' of undefined
    at t.show (vendor.js:167584)
    at vendor.js:167584
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (polyfills.js:2743)
    at Object.onInvokeTask (vendor.js:56347)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (polyfills.js:2742)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (polyfills.js:2510)
    at push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask (polyfills.js:2818)
    at ZoneTask.invoke (polyfills.js:2807)
    at timer (polyfills.js:4376)

What is the right way to use it across lazy loaded modules?

**Comment by SS2095** [comment]
In my app.component.html
    `<h1 joyrideStep="firstStep" title="Welcome!"></h1>`

In my lazy-loaded module account module -> login.component,html
`<h1 joyrideStep="secondStep" title="Login "></h1>`

In my account-routing.module.ts
```
const routes: Routes = [
  {
    path: '',
    component: LoginComponent
  }
.....
```

In my app-routing.module.ts

```
  {
    path: '',
    redirectTo: 'account',
    pathMatch: 'full'
  },
  {
    path: 'account',
    loadChildren: './account/account.module#AccountModule'
  },
```

In my app.component.ts
```
ngOnInit() {
    this.joyrideService.startTour({ steps: ['firstStep', 'secondStep@account'] });
  }
```

I still get the same error as I've mentioned above.

**Comment by tnicola** [comment]
Looking at the routes config in your code example it seems that `firstStep` will be under the `account` route. Because the default root empty route is always redirected to `account` in your case. Can you try with: `steps: ['firstStep@account', 'secondStep@account']` ?

**Comment by SS2095** [comment]
The first step shows up no problem.That error pops up on the second step.

**Comment by tnicola** [comment]
Ok, it makes sense. Your solution should be the right one. I'll try to reproduce this error and I'll let you know soon!

**Comment by tnicola** [comment]
Hi, 
I've fixed the bug with the lazy loaded modules. You can try the fix with the new version: 2.0.1.
Just import `JoyrideModule.forRoot()` in your `AppModule`. Import instead `JoyrideModule.forChild()` in your lazy loaded modules. Let me know if it works.

**Comment by SS2095** [comment]
It works.Thanks for the quick fix!

**Comment by B1ll1** [comment]
I'm having this exact same problem. I imported JoyrideModule.forRoot() in my AppModule. And inside my component module I imported it as JoyrideModule.forChild() but still got the same error.

**Comment by tnicola** [comment]
Ok. So you're using lazy loaded modules, right?Are all your targets/steps visible in DOM?Are you able to start the tour and navigate before getting the error? Could you give me a simple example about your steps?
