### ISSUE TITLE
Step ID is created with the route the component is initialized on

### ISSUE THREAD

**Issue by tb9-Mason** [tnicola/ngx-joyride#7]
I am adding the `joyrideStep` directive to an element that is part of my app's main layout. In my step order, I want to show it on an inner page to fit in with the flow of my tour. I noticed that sometimes the step would show and sometimes it wouldn't. 

After doing some digging it looks like the issue is that the step ID that's created in `ngAfterViewInit` in the joyride directive appends the current route to the ID of the created step. The route that I want to show the step on isn't always the same as the route the step is initialized on, so when `sortSteps` is called in the `JoyrideStepsContainerService`, the `stepName` I registered and the `step.id` aren't the same and therefore is not included in `this.steps`.

Could we provide the route name that we'd like the step to be registered on so that the ID is generated properly? Alternatively, is there some way we could indicate in the step name or inputs that the step isn't dependent on a route?

**Comment by tnicola** [comment]
Hi @tb9-Mason , 
When you say that sometimes the step would show and sometimes not, you are navigating your app in a different order for the two cases, right? Is it your step on the root route? 

Lets suppose you have 2 routes: `routeA` and `routeB`:
What you're saying is that its behaviour is chameleonic, sometimes it is initalized with `routeA` and sometimes with `routeB`, depending on which page is loaded first, is it right?

I'll have a look on this. Anyway, maybe the cleanest solution could be use the `stepName` as `ID`, without the route; in this way the stepName should be unique across all the app routes.

**Comment by tnicola** [comment]
Alright then, I'll try to reproduce it and i will fix it in the next days!

**Comment by tnicola** [comment]
Hi @tb9-Mason ,
This issue should be fixed in the latest version 2.0.2. I removed the `name + route` check, now the lookup is only on the `name`. Let me know if it works.

**Comment by tnicola** [comment]
Closing the issue.
