### ISSUE TITLE
Scroll to the end of the page

### ISSUE THREAD

**Issue by shifenis** [tnicola/ngx-joyride#78]
If the page is long more than the viewport, when the `tour` starts, it scrolls down to the end of the page.  
A possible workaround (i have the component in the top of the page) is use `window.scroll(0, 0)`. But if the component is in the middle, i'm not able to do it.

P.S I'm using a `forRoot-forChild` structure (lazy modules)

**Versions:**
 - Tested on Chrome 77.0.3865.90
 - Angular 7.0.7
-  NgX-joyride 2.2.10

**Comment by TommyDufmats** [comment]
I have the same issue, any solution for this??

**Comment by shifenis** [comment]
@TommyDufmats I did not found any workaround for this issue, so i i had to choose another approach

**Comment by TheMalloum** [comment]
+1

**Comment by fpichlou** [comment]
You can set `overflow:auto|scroll|overlay` to one of the parent element for solving this issue.

**Comment by ksilz** [comment]
Big thank you, @fpichlou! `overflow: auto` on my parent div prevented the scrolling wonderfully!

**Comment by GustavoRodrigues94** [comment]
Olá pessoal, consegui resolver o problema que estava ocorrendo comigo no Angular 9. Estava enviando o scroll para o final da página. Então, eu resolvi setando o scroll manualmente em cada etapa. Caso alguém ainda estiver com esse problema, contate-me

**Comment by hieunh1801** [comment]
> Big thank you, @fpichlou! `overflow: auto` on my parent div prevented the scrolling wonderfully!

very helpful for me, thanks

**Comment by ankushchicmic** [comment]
I'm getting the same kind of issue once scroll to the middle of the page joy ride pointer shows correctly but the highlighted area is in the wrong direction as shown in the attachments below.
![image](https://github.com/tnicola/ngx-joyride/assets/62688597/81e87bf3-f05c-4112-81a0-428c05b1ac0e)

2. Pointer is correct
![image](https://github.com/tnicola/ngx-joyride/assets/62688597/fce129c2-114a-4238-a7bb-8f428e1b224d)
2.1. but the highlighted area is shown above the section
![image](https://github.com/tnicola/ngx-joyride/assets/62688597/ef28aa82-7348-46f2-8782-e32b561ad771)
