### ISSUE TITLE
Should install for Angular 8 without warning

### ISSUE THREAD

**Issue by ianjamieson** [tnicola/ngx-joyride#83]
**Describe the bug**
Installing package for Angular 8+ shows warnings.

**To Reproduce**
1. Create an Angular project with version >= 8
1. Run `npm install ngx-joyride --save`

**Expected behaviour**
Should install without warning

**Actual behaviour**
Shows the following warnings after install

```
npm WARN ngx-joyride@2.2.10 requires a peer of @angular/core@>=4.0.0 <8.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-joyride@2.2.10 requires a peer of @angular/common@>=4.0.0 <8.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-joyride@2.2.10 requires a peer of @angular/compiler@>=4.0.0 <8.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-joyride@2.2.10 requires a peer of @angular/router@>=4.0.0 <8.0.0 but none is installed. You must install peer dependencies yourself.
```

**Details (please complete the following information):**
- Angular versions:
```
"@angular/animations": "8.1.2",
    "@angular/cdk": "8.1.1",
    "@angular/common": "8.1.2",
    "@angular/core": "8.1.2",
    "@angular/flex-layout": "8.0.0-beta.27",
    "@angular/forms": "8.1.2",
    "@angular/material": "8.1.1",
    "@angular/platform-browser": "8.1.2",
    "@angular/platform-browser-dynamic": "8.1.2",
    "@angular/router": "8.1.2",
```
- Joyride:
```
"ngx-joyride": "2.2.10",
```

**Comment by jpcarnes** [comment]
Hey @ianjamieson did you ever get this working with an angular 8+ app? really liking this library but needed it to be compatible with 8+

**Comment by ianjamieson** [comment]
@jpcarnes - hey, yeh I am using on an angular 9 project at the moment. Although I am still seeing these warnings. 

I haven't encountered any issues as of yet. The warnings are just suggesting that `ngx-joyride` have not updated their dependencies to accept angular > 8. Likely meaning they haven't tested it themselves on later Angular versions.

Good luck!

**Comment by jpcarnes** [comment]
@ianjamieson appreciate the fast response! Ended up switching to intro.js for my use case because it had a little more functionality than ngx-joyride.

**Comment by jpcarnes** [comment]
@ianjamieson when you implemented this did you have to add anything like <ngx-joyride-template> <ngx-joyride-template> to the app.component.html file?

I follwed the steps in the readme but nothing happend when I try to start the function through a button that has my ngx-joyride commands in them.

**Comment by ianjamieson** [comment]
As far as I recall, to initialise joyride I have added:

`<joyrideStep joyrideStep="stepIntroduction" [stepContent]="stepIntroductionContent" [nextTemplate]="nextButton"
             stepPosition="center"></joyrideStep>`

Which is referring to templates like:

```
<ng-template #stepIntroductionContent>
  Step content
</ng-template>
```

I haven't added this to `app.component.html`, but I have added it to the component markup that I want to use joyride on.

Hope this helps

**Comment by dhiegoatencio** [comment]
@jpcarnes, yes it works with angular 8 projects

**Comment by tnicola** [comment]
I updated the dependencies, so you shouldn't see the the warnings anymore.
