### ISSUE TITLE
how to use with angularjs?

### ISSUE THREAD

**Issue by Shemesh** [tnicola/ngx-joyride#88]
hi,
we got a mixed application that have both angular 7 and angularjs (1.5)...
how can we use joyride in angularjs?

**Comment by suad2017** [comment]
Hi @tnicola,
I also have a mixed application that have both angular 2+ and angularjs (1.5)...
how can we use ngx-joyride in angularjs?
Thanks,
Suad

**Comment by tnicola** [comment]
Unfortunately the lib is only supporting Angular, not AngularJS, you can just use it in your Angular part of the app. I don't think I will have the time to support also AngularJS. If you want to contribute feel free to.
